"""
Diagnoser — Phase 4 of VerifyAgent

Analyzes test execution failures and produces root cause analysis
with severity ratings and suggested fixes.
"""

import json
from src.llm.gemini_client import GeminiClient

SYSTEM_PROMPT = """You are a senior debugging engineer. You are given:
1. Source code that was generated by an AI
2. A specification of what the code should do
3. Test results showing which tests passed and which failed

Your job is to analyze the failures and provide:
- Root cause: What is fundamentally wrong in the code?
- Severity: critical (security/data loss), high (incorrect results), medium (edge case failure), low (cosmetic)
- Category: logic_error, off_by_one, missing_validation, type_error, state_bug, missing_edge_case, security_flaw
- Suggested fix: The specific code change needed

Be precise. Don't hallucinate issues that aren't demonstrated by the test results.
Every diagnosis must be backed by a specific failing test."""


def diagnose_failures(
    llm: GeminiClient,
    code: str,
    spec: str,
    test_results: list[dict],
) -> list[dict]:
    """
    Analyze test failures and produce diagnoses.

    Returns a list of diagnosed bugs, each with:
        - bug_id: str
        - root_cause: str
        - severity: str (critical/high/medium/low)
        - category: str
        - failing_tests: list[str]
        - suggested_fix: str (code diff or description)
        - confidence: float (0-1)
    """
    # Only send failed tests for diagnosis
    failures = [r for r in test_results if not r.get("passed", True)]

    if not failures:
        return []

    prompt = f"""Analyze these test failures for the code below.

## SPECIFICATION:
{spec}

## CODE:
```python
{code}
```

## FAILED TESTS:
{json.dumps(failures, indent=2)}

## PASSING TESTS (for context):
{json.dumps([r for r in test_results if r.get("passed", False)], indent=2)}

Identify the distinct bugs that caused these failures. Group related failures together.

Return a JSON array of bugs. Each bug must have:
- "bug_id": "BUG-001", "BUG-002", etc.
- "root_cause": clear explanation of what's wrong
- "severity": "critical", "high", "medium", or "low"
- "category": one of "logic_error", "off_by_one", "missing_validation", "type_error", "state_bug", "missing_edge_case", "security_flaw"
- "failing_tests": list of test names that this bug caused to fail
- "suggested_fix": the specific Python code that should replace the buggy section
- "confidence": float 0.0 to 1.0 — how confident you are this is the root cause
- "evidence": quote the specific test output that proves this bug exists

Return ONLY the JSON array."""

    result = llm.generate_json(
        prompt=prompt,
        system_instruction=SYSTEM_PROMPT,
        temperature=0.1,
    )

    if isinstance(result, list):
        return result
    return result.get("bugs", result.get("diagnoses", []))
